language: node_js
node_js:
    - node
before_install:
    - sudo apt-get install libxtst-dev libpng++-dev
install:
    - npm ci
script:
    - npm run lint
    - npm run compile
    - npm run test
    - npm run cuc
