name: Node.js CI

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Install robotjs deps
              run: sudo apt-get install libxtst-dev libpng++-dev
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - name: Compile Typescript
              run: npm run compile
            - name: Generate coverage
              run: npm run coverage
            - name: E2E tests (Cucumber.js)
              run: npm run cuc
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
